use serde::{Deserialize, Serialize};


#[derive(Debug, Serialize, Deserialize)]
pub struct CloseOrderAlgo {}

#[derive(Debug, Serialize, Deserialize)]
pub struct OKXPositionData {
    adl: String,
    availPos: Option<String>,
    avgPx: String,
    baseBal: Option<String>,
    baseBorrowed: Option<String>,
    baseInterest: Option<String>,
    bePx: String,
    bizRefId: Option<String>,
    bizRefType: Option<String>,
    cTime: String,
    ccy: String,
    clSpotInUseAmt: Option<String>,
    closeOrderAlgo: Vec<CloseOrderAlgo>,
    deltaBS: Option<String>,
    deltaPA: Option<String>,
    fee: String,
    fundingFee: String,
    gammaBS: Option<String>,
    gammaPA: Option<String>,
    idxPx: String,
    imr: String,
    instId: String,
    instType: String,
    interest: Option<String>,
    last: String,
    lever: String,
    liab: Option<String>,
    liabCcy: Option<String>,
    liqPenalty: String,
    liqPx: String,
    margin: Option<String>,
    markPx: String,
    maxSpotInUseAmt: Option<String>,
    mgnMode: String,
    mgnRatio: String,
    mmr: String,
    notionalUsd: String,
    optVal: Option<String>,
    pTime: String,
    pendingCloseOrdLiabVal: Option<String>,
    pnl: String,
    pos: String,
    posCcy: Option<String>,
    posId: String,
    posSide: String,
    quoteBal: Option<String>,
    quoteBorrowed: Option<String>,
    quoteInterest: Option<String>,
    realizedPnl: String,
    spotInUseAmt: Option<String>,
    spotInUseCcy: Option<String>,
    thetaBS: Option<String>,
    thetaPA: Option<String>,
    tradeId: String,
    uTime: String,
    upl: String,
    uplLastPx: String,
    uplRatio: String,
    uplRatioLastPx: String,
    usdPx: Option<String>,
    vegaBS: Option<String>,
    vegaPA: Option<String>,
}